### ISSUE TITLE
What's new here ?

### ISSUE THREAD

**Issue by vincedev** [jnozzi/cocoadev.com#10]
Is work on cocoadev.com still in progress ?
Is the site definitely down ?

**Comment by jnozzi** [comment]
Frankly, there's been zero progress for years. I keep the content up and keep paying to maintain the domain so this once-great resource doesn't disappear (since the original creator/maintainer announced he could no longer keep up with wikispam, etc. and wanted someone to maintain its archives). 

Over the years I'd put out several calls for help cleaning up the content (converting the old wiki markup to Markdown, reorganizing, etc.) so we can maintain it via pull requests to keep spammers / vandals out, but all I received were several empty promises with zero activity and a number of #$$hole-ish e-mails ridiculing me for "destroying" CocoaDev.com (rewrite history much?) and / or not spending my own time and money to do it all myself (because I don't have other responsibilities and I *owe* them something, after all). Also got taken to task for putting my name in the footer as a maintainer (because how *dare* I take credit for spending time and money to take over maintaining something that makes me zero money in return). Not the greatest incentives from a once-vibrant and mutually-supportive community.

So yes, editing is currently off the table until/unless I can get some real, meaningful help in not only cleaning up the current content but in managing pull requests for edits. At the very least, maintaining it here vs. passing it on to someone else who "promises to do more with it" enforces public accountability for not turning it into a cash grab or letting the domain lapse.

Not that I'm bitter over how I've been treated for doing something nice for the community or anything. ;-)
